import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],

  products: [
    {
      name: 'Чашка Keep Cup Original 340 ml',
      slug: 'keep-cup',
      category: 'Екопосуд',
      image: '/images/cup.jpeg',
      price: 570,
      brand: 'Keep Cup',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Ваш стильний eco-friendly аксесуар',
    },
    {
      name: 'Біорозкладні пакети "Ecomaizing" 35L',
      slug: 'packet',
      category: 'Товари для дому',
      image: '/images/packet.jpg',
      price: 80,
      brand: 'Ecomaizing',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'Продукт з органічної сировини',
    },
    {
      name: 'Свічка з натурального воску',
      slug: 'candle',
      category: 'Товари для дому',
      image: '/images/candle.jpg',
      price: 460,
      brand: 'Coconut Home',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'Декор для вашого простору',
    },
    {
      name: 'Контейнер для сортування пластику',
      slug: 'container',
      category: 'Товари для дому',
      image: '/images/container.jpg',
      price: 390,
      brand: 'ZeroWaste',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Контейнер призначений для багаторазового використання',
    },
    {
      name: 'Екологічний пральний порошок 1 кг',
      slug: 'soap',
      category: 'Товари для дому',
      image: '/images/soap.jpg',
      price: 195,
      brand: 'DeLaMark',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'Порошок для ефективного прання білих речей',
    },
    {
      name: 'Настільна гра ЕКО-МЕМО',
      slug: 'game',
      category: 'Товари для дітей',
      image: '/images/game.jpg',
      price: 675,
      brand: 'ЕКО-МЕМО',
      rating: 4.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Вікова категорія: 4+років',
    },
  ],
};

export default data;
